CLASS zcl_amdp_00 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_amdp_marker_hdb .

    CLASS-METHODS : GET_FLIGHTS FOR TABLE FUNCTION ZS4D430_CDS30.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_amdp_00 IMPLEMENTATION.

  METHOD get_flights BY DATABASE FUNCTION
                FOR HDB LANGUAGE SQLSCRIPT
                USING SFLIGHT .


*  ///--- 1. MUST HAVE RETURN
*  // 2. MUST THAVE ALL THE FIELDS FROM THE CDS
*  // 3. THE MANDT FIELD ALSO
*
*
*  4. USING DATABASE TABLE
*  5. PARAMTERS OF THE CDS

    RETURN

        SELECT MANDT, CARRID, CONNID, FLDATE,PRICE
          FROM SFLIGHT
          WHERE  CONTAINS( CARRID , :AIRLINE , FUZZY );


  ENDMETHOD.

ENDCLASS.
